# 例外処理について
  - 例外が発生するとそれ以降の処理が実行されずそこで処理が止まる。

## 例外処理の補足
  ```
  puts 'Start'

  1 + '10' # IntとStrの式

  puts 'End'
  ```
  `1 + '10'`で処理が止まり、`puts 'End'`が実行されない

## 例外を補足して処理を実行する。
  以下のように書くことで例外処理が発生してもプログラムを続行したい場合の書き方
  ```
  begin
    # 例外処理が発生しうる処理
  rescue
    # 例外が発生した場合の処理
  end 
  ```

  先程のセクションの内容を取り込んで実行すると
  ```
  puts 'Start'

  begin
    1 + '10'
  rescue
    puts '例外処理が発生したが、このまま実行する'
  end

  puts 'End'
  ```

## 例外オブジェクトから情報を取得する
  - 例外自身もオブジェクト
  - 例外オブジェクトのメソッドを呼ぶ出すことで、発生した例外の情報を取得することができる。
  
  - 代表的なメソッド
    - messageメソッド: 例外発生した際のエラーメッセージを返す
    - backtreeメソッド: バックトレース情報(メソッドの呼出履歴)を返す

  
  構文
  ```
    begin
      # 例外が発生しうる処理
    rescue => 例外オブジェクトを格納する変数
      # 例外が発生した場合の処理
    end
  ```

  例
  ```
    begin
      1/0
    rescue => e
      puts "エラークラス: #{e.class}"
      puts "エラーメッセージ: #{e.message}"
      puts "バックトレース -----"
      puts "e.backtree"
      puts "-----"
    end
  ```